name: 3. Test Language Server and publish
run-name: 3. Test Language Server and publish - ${{ inputs.trigger_reason }}

on:
  workflow_dispatch:
    inputs:
      release_channel:
        description: "Identifies whether we're publishing an insider or stable release of the extension"
        required: true
        type: choice
        options:
          - insider
          - stable
      branch:
        description: 'Branch to run run this workflow on'
        required: true
      extension_version:
        description: 'VS Code extension version. When provided, it will trigger the next workflow to bump the LS version in the extension.'
      trigger_reason:
        description: 'Information about what caused the publishing process in the first place.'

permissions:
  id-token: write # required for OIDC / Trusted Publishers

env:
  PRISMA_TELEMETRY_INFORMATION: 'language-tools 3_LS_unit_tests_publish.yml'
  LS_NPM_CHANNEL: ${{ github.event.inputs.release_channel == 'stable' && 'latest' || 'dev' }}

jobs:
  tests:
    name: Run tests
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PRISMA_BOT_TOKEN }}
          ref: ${{ github.event.inputs.branch }}
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install
      - name: Build Language Server
        run: pnpm --filter @prisma/language-server build
      - name: Run Language Server tests
        run: pnpm --filter @prisma/language-server test

  bump:
    name: Bump Language Server version
    needs: [tests]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Update npm to support Trusted Publishers
        run: npm install -g npm@^11.5
      - name: Print inputs
        run: |
          echo ${{github.event.inputs.release_channel}}
          echo ${{github.event.inputs.extension_version || 'not provided'}}
          echo ${{github.event.inputs.branch}}
          echo ${{github.event.inputs.trigger_reason || 'not provided'}}
      - name: Install Dependencies
        run: pnpm install
      - name: Build Language Server
        run: pnpm --filter @prisma/language-server build
      - name: Publish Language Server to npm
        run: pnpm --filter @prisma/language-server publish --tag ${{ env.LS_NPM_CHANNEL }} --access public --no-git-checks
      - name: Trigger next workflow for bumping Language Server in extension
        if: ${{ github.event.inputs.extension_version != '' }}
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: 4. Bump LS in VSCode extension
          token: ${{ secrets.PRISMA_BOT_TOKEN }}
          inputs: '{ "release_channel": "${{ github.event.inputs.release_channel }}", "extension_version": "${{ github.event.inputs.extension_version }}", "branch": "${{ github.event.inputs.branch }}", "trigger_reason": "${{github.event.inputs.trigger_reason}}" }'
