name: Insider Check for Update + Automated Publish

on:
  schedule:
   # the script takes about 12-19 minutes, so in order to not have two processes start together, this is set to 20
    - cron: '*/20 * * * *'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ENVIRONMENT: ${{ secrets.ENVIRONMENT }}

jobs:
  setup:
    name: Check for Updates
    runs-on: ubuntu-latest
    if: endsWith(github.ref, '/master')
    outputs:
      version: ${{ steps.check_for_updates.outputs.version }}
      lsp-not-published: ${{ steps.check_lsp_version.outputs.lsp-not-published }}
    steps:
      - uses: actions/checkout@v2
       # serialize this workflow run
      - name: Turnstyle
        uses: softprops/turnstyle@v1
        # https://github.com/softprops/turnstyle/issues/13
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Dependencies
        run: npm install
      - name: Check for Update
        run: npm run vsce:check "dev" 
        id: check_for_updates
      - name: Bump versions
        if: ${{ steps.check_for_updates.outputs.version }}
        run: npm run vsce:bump "dev" ${{ steps.check_for_updates.outputs.version }}
      - name: Check existing LSP version
        if: ${{ steps.check_for_updates.outputs.version }}
        id: check_lsp_version
        run: npm run check:lsp ${{ steps.check_for_updates.outputs.version }}
  
  test-lsp:
    name: Test LSP
    needs: setup
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    if: ${{ needs.setup.outputs.lsp-not-published }}
    steps:
      - uses: actions/checkout@v2
       # serialize this workflow run
      - name: Turnstyle
        uses: softprops/turnstyle@v1
        # https://github.com/softprops/turnstyle/issues/13
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Dependencies
        run: npm install
      - name: Bump versions
        # Jobs do not share workspace --> bump versions again
        if: ${{ needs.setup.outputs.version }}
        run: npm run vsce:bump "dev" ${{ needs.setup.outputs.version }}
      - name: Install Dependencies in LSP
        run: cd packages/language-server && npm install
      - name: Compile LSP
        run: cd packages/language-server && npm run build
      - name: LSP unit tests
        run: cd packages/language-server && npm test

  publish-lsp:
    name: Publish LSP to npm
    needs: [setup, test-lsp]
    runs-on: ubuntu-latest
    if: ${{ needs.setup.outputs.lsp-not-published }}
    steps:
      - uses: actions/checkout@v2
       # serialize this workflow run
      - name: Turnstyle
        uses: softprops/turnstyle@v1
        # https://github.com/softprops/turnstyle/issues/13
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Dependencies
        run: npm install
      - name: Bump versions
        # Jobs do not share workspace --> bump versions again
        if: ${{ needs.setup.outputs.version }}
        run: npm run vsce:bump "dev" ${{ needs.setup.outputs.version }}
      - name: Install Dependencies in LSP
        run: cd packages/language-server && npm install
      - name: Compile LSP
        run: cd packages/language-server && npm run build
      - name: Publish LSP to npm
        # Setup .npmrc file to publish to npm
        uses: actions/setup-node@v1
        with: 
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - run: cd packages/language-server && npm publish --tag dev --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN}}

  test-extension:
    name: Extension integration tests
    needs: [setup, test-lsp, publish-lsp]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    if: always() &&  ${{ needs.setup.outputs.version }}
    steps: 
      - uses: actions/checkout@v2
       # serialize this workflow run
      - name: Turnstyle
        uses: softprops/turnstyle@v1
        # https://github.com/softprops/turnstyle/issues/13
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Dependencies
        if: ${{ needs.setup.outputs.version }}
        run: npm install
      - name: Bump versions
        # Jobs do not share workspace --> bump versions again
        if: ${{ needs.setup.outputs.version }}
        run: npm run vsce:bump "dev" ${{ needs.setup.outputs.version }}
      - name: Install Dependencies
        if: ${{ needs.setup.outputs.version }}
        run: npm install
      - name: Compile
        if: ${{ needs.setup.outputs.version }}
        run: npm run compile
      - name: Headless e2e tests
        if: ${{ needs.setup.outputs.version }}
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: npm run test

  publish-open-vsx:
    name: Publish insider extension to open-vsx.org
    runs-on: ubuntu-latest
    needs: [setup, test-extension]
    if: ${{ needs.setup.outputs.version }}
    env: 
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      SLACK_CHANNEL: feed-language-tools
      SLACK_USERNAME: Prismo
      SLACK_ICON_EMOJI: ":ship:"
      SLACK_MESSAGE: ${{ needs.setup.outputs.version }}
    steps:
      - uses: actions/checkout@v2
       # serialize this workflow run
      - name: Turnstyle
        uses: softprops/turnstyle@v1
        # https://github.com/softprops/turnstyle/issues/13
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Dependencies
        run: npm install
      - name: Bump versions
        # Jobs do not share workspace --> bump versions again
        run: npm run vsce:bump "dev" ${{ needs.setup.outputs.version }}
      - name: Install Dependencies
        run: npm install
      - name: Publish extension to open-vsx.org
        env:
          OPEN_VSX_ACCESS_TOKEN: ${{ secrets.OPEN_VSX_ACCESS_TOKEN }}
        run: cd packages/vscode && npx ovsx publish -p "$OPEN_VSX_ACCESS_TOKEN"
      - name: Slack Notification on Failure
        if: ${{ needs.setup.result == 'failure' || needs.test-extension.result == 'failure' || failure() }}
        uses: rtCamp/action-slack-notify@v2.0.2
        env:  
          SLACK_TITLE: "Publishing insider to open-vsx on new Prisma CLI version failed :x:"
          SLACK_COLOR: '#FF0000'
      - name: Slack Notification on Success
        if: ${{ needs.test-extension.result == 'success' && success() }}
        uses: rtCamp/action-slack-notify@v2.0.2
        env:  
          SLACK_TITLE: "Published insider to open-vsx on new Prisma CLI version :white_check_mark:"
          SLACK_COLOR: '#008000'

  publish-marketplace: 
    name: Publish insider extension to marketplace
    runs-on: ubuntu-latest
    needs: [setup, test-extension, publish-open-vsx]
    if: always() && ${{ needs.setup.outputs.version }}
    env: 
      AZURE_DEVOPS_PERSONAL_ACCESS_TOKEN: ${{ secrets.AZURE_DEVOPS_PERSONAL_ACCESS_TOKEN }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      SLACK_CHANNEL: feed-language-tools
      SLACK_USERNAME: Prismo
      SLACK_ICON_EMOJI: ":ship:"
      SLACK_MESSAGE: ${{ needs.setup.outputs.version }}
    steps:
      - uses: actions/checkout@v2
       # serialize this workflow run
      - name: Turnstyle
        uses: softprops/turnstyle@v1
        # https://github.com/softprops/turnstyle/issues/13
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Dependencies
        run: npm install
      - name: Bump versions
        # Jobs do not share workspace --> bump versions again
        run: npm run vsce:bump "dev" ${{ needs.setup.outputs.version }}
      - name: Install Dependencies
        run: npm install
      - name: Publish Extension to Marketplace
        run: npm run vsce:publish "dev" ${{ needs.setup.outputs.version }}
      - name: Slack Notification on Failure
        if: ${{ needs.setup.result == 'failure' || needs.test-extension.result == 'failure' || failure() }}
        uses: rtCamp/action-slack-notify@v2.0.2
        env:  
          SLACK_TITLE: "Publishing insider to Marketplace on new Prisma CLI version failed :x:"
          SLACK_COLOR: '#FF0000'
      - name: Slack Notification on Success
        if: ${{ needs.test-extension.result == 'success' && success() }}
        uses: rtCamp/action-slack-notify@v2.0.2
        env:  
          SLACK_TITLE: "Published insider to Marketplace on new Prisma CLI version :white_check_mark:"
          SLACK_COLOR: '#008000'
      