name: Check for Update + Automated Publish

on:
  push:
    branches:
      - master
  schedule:
    - cron: '*/5 * * * *'

env:
  AZURE_DEVOPS_PERSONAL_ACCESS_TOKEN: ${{ secrets.AZURE_DEVOPS_PERSONAL_ACCESS_TOKEN }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  PRODUCTION: ${{ secrets.PRODUCTION }}

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: endsWith(github.ref, '/master')
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Run headless test
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: npm run test
      - name: Publish Extension as Patch
        run: yarn vsce:check "latest"

  publish-dev:
    name: Publish Dev
    runs-on: ubuntu-latest
    if: endsWith(github.ref, '/master')
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Run headless test
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: npm run test
      - name: Publish Extension as Patch
        run: yarn vsce:check "dev"
