name: Check for Update + Automated Publish

on:
  push:
    branches:
      - master
  schedule:
    - cron: '*/5 * * * *'

env:
  AZURE_DEVOPS_PERSONAL_ACCESS_TOKEN: ${{ secrets.AZURE_DEVOPS_PERSONAL_ACCESS_TOKEN }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  PRODUCTION: ${{ secrets.PRODUCTION }}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: endsWith(github.ref, '/master')
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Check for Update
        run: yarn vsce:check "latest"
        id: check_for_updates
      - name: Bump versions
        if: ${{ steps.check_for_updates.outputs.new_updates }}
        run: yarn vsce:bump "latest"
      - name: Compile
        run: yarn compile
      - name: Run headless e2e tests
        if: ${{ steps.check_for_updates.outputs.new_updates }}
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: npm run test
      - name: Publish Extension as Patch
        if: ${{ steps.check_for_updates.outputs.new_updates }}
        run: yarn vsce:publish "latest"
      - name: Slack Notification on Failure
        if: ${{ failure() && steps.check_for_updates.outputs.new_updates }}
        uses: rtCamp/action-slack-notify@v2.0.2
        env:  
          SLACK_CHANNEL: feed-vscode
          SLACK_MESSAGE: "Publishing stable failed :x:"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_ICON_EMOJI: ":ship:"
          SLACK_USERNAME: vscode-actions
          SLACK_COLOR: '#FF0000'

      - name: Slack Notification on Success
        if: ${{ success() && steps.check_for_updates.outputs.new_updates }}
        uses: rtCamp/action-slack-notify@v2.0.2
        env:  
          SLACK_CHANNEL: feed-vscode
          SLACK_MESSAGE: "Published stable :white_check_mark:"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_ICON_EMOJI: ":ship:"
          SLACK_USERNAME: vscode-actions
          SLACK_COLOR: '#008000'

  publish-insider:
    name: Publish Insider
    runs-on: ubuntu-latest
    if: endsWith(github.ref, '/master')
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Check for Update
        run: yarn vsce:check "dev"
        id: check_for_updates
      - name: Bump versions
        if: ${{ steps.check_for_updates.outputs.new_updates }}
        run: yarn vsce:bump "dev"
      - name: Compile
        run: yarn compile
      - name: Run headless e2e tests
        if: ${{ steps.check_for_updates.outputs.new_updates }}
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: npm run test
      - name: Publish Extension as Patch
        if: ${{ steps.check_for_updates.outputs.new_updates }}
        run: yarn vsce:publish "dev"
      - name: Slack Notification on Failure
        if: ${{ failure() && steps.check_for_updates.outputs.new_updates }}
        uses: rtCamp/action-slack-notify@v2.0.2
        env:  
          SLACK_CHANNEL: feed-vscode
          SLACK_MESSAGE: "Publishing Insider failed :x:"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_ICON_EMOJI: ":ship:"
          SLACK_USERNAME: vscode-actions
          SLACK_COLOR: '#FF0000'
      - name: Slack Notification on Success
        if: ${{ success() && steps.check_for_updates.outputs.new_updates }}
        uses: rtCamp/action-slack-notify@v2.0.2
        env:  
          SLACK_CHANNEL: feed-vscode
          SLACK_MESSAGE: "Published Insider :white_check_mark:"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_ICON_EMOJI: ":ship:"
          SLACK_USERNAME: vscode-actions
          SLACK_COLOR: '#008000'

      
