name: Check for Update + Automated Publish

on:
  push:
    branches:
      - master
  schedule:
    - cron: '*/5 * * * *'

env:
  AZURE_DEVOPS_PERSONAL_ACCESS_TOKEN: ${{ secrets.AZURE_DEVOPS_PERSONAL_ACCESS_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: endsWith(github.ref, '/master')
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Check for Update
        run: npm run vsce:check "latest" 
        id: check_for_updates
      - name: Bump versions
        if: ${{ steps.check_for_updates.outputs.new_updates }}
        run: npm run vsce:bump "latest" 
        id: bump_versions
      - name: Publish LSP to npm
        if: ${{ steps.check_for_updates.outputs.new_updates }}
        # Setup .npmrc file to publish to npm
        uses: actions/setup-node@v1
        with: 
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - run: cd packages/language-server && npm publish --access public
        if: ${{ steps.check_for_updates.outputs.new_updates }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN}}
      - name: Install Dependencies
        run: npm install
      - name: Compile
        run: npm run compile
      - name: Run headless e2e tests
        if: ${{ steps.check_for_updates.outputs.new_updates }}
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: npm run test
      - name: Remove binaries
        if: ${{ steps.check_for_updates.outputs.new_updates }}
        run: rm packages/vscode/node_modules/@prisma/language-server/dist/src/prisma-fmt*
      - name: Publish Extension as Patch
        if: ${{ steps.check_for_updates.outputs.new_updates }}
        run: npm run vsce:publish "latest"
      - name: Slack Notification on Failure
        if: ${{ failure() && steps.check_for_updates.outputs.new_updates }}
        uses: rtCamp/action-slack-notify@v2.0.2
        env:  
          SLACK_CHANNEL: feed-vscode
          SLACK_TITLE: "Publishing stable failed :x:"
          SLACK_MESSAGE: ${{ steps.bump_versions.outputs.version }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_ICON_EMOJI: ":ship:"
          SLACK_USERNAME: vscode-actions
          SLACK_COLOR: '#FF0000'

      - name: Slack Notification on Success
        if: ${{ success() && steps.check_for_updates.outputs.new_updates }}
        uses: rtCamp/action-slack-notify@v2.0.2
        env:  
          SLACK_CHANNEL: feed-vscode
          SLACK_TITLE: "Published stable :white_check_mark:"
          SLACK_MESSAGE: ${{ steps.bump_versions.outputs.version }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_ICON_EMOJI: ":ship:"
          SLACK_USERNAME: vscode-actions
          SLACK_COLOR: '#008000'

  publish-insider:
    name: Publish Insider
    runs-on: ubuntu-latest
    if: endsWith(github.ref, '/master')
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Check for Update
        run: npm run vsce:check "dev"
        id: check_for_updates
      - name: Bump versions
        if: ${{ steps.check_for_updates.outputs.new_updates }}
        run: npm run vsce:bump "dev"
        id: bump_versions
      - name: Publish LSP to npm
        if: ${{ steps.check_for_updates.outputs.new_updates }}
        # Setup .npmrc file to publish to npm
        uses: actions/setup-node@v1
        with: 
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - run: cd packages/language-server && npm publish --access public
        if: ${{ steps.check_for_updates.outputs.new_updates }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN}}
      - name: Install Dependencies
        run: npm install
      - name: Compile
        run: npm run compile
      - name: Run headless e2e tests
        if: ${{ steps.check_for_updates.outputs.new_updates }}
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: npm run test
      - name: Remove binaries
        if: ${{ steps.check_for_updates.outputs.new_updates }}
        run: rm packages/vscode/node_modules/@prisma/language-server/dist/src/prisma-fmt*
      - name: Publish Extension as Patch
        if: ${{ steps.check_for_updates.outputs.new_updates }}
        run:  npm run vsce:publish "dev"
      - name: Slack Notification on Failure
        if: ${{ failure() && steps.check_for_updates.outputs.new_updates }}
        uses: rtCamp/action-slack-notify@v2.0.2
        env:  
          SLACK_CHANNEL: feed-vscode
          SLACK_TITLE: "Publishing Insider Version failed :x:"
          SLACK_MESSAGE: ${{ steps.bump_versions.outputs.version }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_ICON_EMOJI: ":ship:"
          SLACK_USERNAME: vscode-actions
          SLACK_COLOR: '#FF0000'
      - name: Slack Notification on Success
        if: ${{ success() && steps.check_for_updates.outputs.new_updates }}
        uses: rtCamp/action-slack-notify@v2.0.2
        env:  
          SLACK_CHANNEL: feed-vscode
          SLACK_TITLE: "Published Insider Version :white_check_mark:"
          SLACK_MESSAGE: ${{ steps.bump_versions.outputs.version }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_ICON_EMOJI: ":ship:"
          SLACK_USERNAME: vscode-actions
          SLACK_COLOR: '#008000'

      